name: test
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        node-version: ['22.x', '24.x']

    name: all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v6
      with:
        version: 11

    - name: Install Dependencies
      run: pnpm i -r

    - name: Run Build
      run: pnpm build

    - name: Run Lint
      run: pnpm lint

    - name: Run Test
      run: pnpm test
